defaults:
  - _self_
  - products: products
  - resources: resources
  - override hydra/launcher: joblib

training:
  name: "training_rldbr"
  n_envs: 10
  total_timesteps: 10000000
  learning_rate: 0.0005
  learning_rate_schedule: linear
  learning_rate_end: 0.00001
  policy_net_arch: [128, 128]
  batch_size: 2048
  n_epochs: 10
  n_steps: 8192
  verbose: 1
  callback_model_prefix: "rldbr_model"
  callback_save_freq: 200000
  tensorboard_log: data/tensorboard_log
  tb_log_name: ${now:%y%m%d%H%M}_${training.name}
  model_save_path: simulations/rl_dbr/models/ppo/${now:%y%m%d%H%M}_${training.name}
  diagnostics_entropy_samples: 512

# Simulation configuration
environment:
  run_until: 300000
  warmup: 0
  monitor_interval: 5000000
  monitor_warmup: 5000000
  delivery_mode: "instantly"
  log_queues: False
  print_mode: None
  memory_size: 10000
  # Schedule
  scheduler_interval: 24
  schedule_max_size: 20
  training: True
  reward:
    lost_sales_multiplier: 3.0
    wip_multiplier: 0.008
    fg_multiplier: 0.004
  load_termination_threshold: 3000
  space_scale_buffer: 100
  space_scale_products: 50

# Hydra config
hydra:
  run:
    dir: data/experiments/${now:%y%m%d%H%M}_${training.name}
  sweep:
    dir: data/experiments
    subdir: ${now:%y%m%d%H%M}_${training.name}_${hydra.job.num}
  launcher:
    n_jobs: 1


